var hierarchy =
[
    [ "RT::Camera", "class_r_t_1_1_camera.html", null ],
    [ "CApp", "class_c_app.html", null ],
    [ "RT::GTform", "class_r_t_1_1_g_tform.html", null ],
    [ "Image", "class_image.html", null ],
    [ "RT::LightBase", "class_r_t_1_1_light_base.html", [
      [ "RT::PointLight", "class_r_t_1_1_point_light.html", null ]
    ] ],
    [ "RT::MaterialBase", "class_r_t_1_1_material_base.html", [
      [ "RT::SimpleMaterial", "class_r_t_1_1_simple_material.html", null ],
      [ "RT::SimpleRefractive", "class_r_t_1_1_simple_refractive.html", null ]
    ] ],
    [ "RT::ObjectBase", "class_r_t_1_1_object_base.html", [
      [ "RT::Cone", "class_r_t_1_1_cone.html", null ],
      [ "RT::Cylinder", "class_r_t_1_1_cylinder.html", null ],
      [ "RT::ObjPlane", "class_r_t_1_1_obj_plane.html", null ],
      [ "RT::ObjSphere", "class_r_t_1_1_obj_sphere.html", null ]
    ] ],
    [ "qbMatrix2< T >", "classqb_matrix2.html", null ],
    [ "qbMatrix2< double >", "classqb_matrix2.html", null ],
    [ "qbVector< T >", "classqb_vector.html", null ],
    [ "qbVector< double >", "classqb_vector.html", null ],
    [ "RT::Ray", "class_r_t_1_1_ray.html", null ],
    [ "RT::Scene", "class_r_t_1_1_scene.html", null ],
    [ "SDL_AssertData", "struct_s_d_l___assert_data.html", null ],
    [ "SDL_atomic_t", "struct_s_d_l__atomic__t.html", null ],
    [ "SDL_AudioCVT", "struct_s_d_l___audio_c_v_t.html", null ],
    [ "SDL_AudioDeviceEvent", "struct_s_d_l___audio_device_event.html", null ],
    [ "SDL_AudioSpec", "struct_s_d_l___audio_spec.html", null ],
    [ "SDL_Color", "struct_s_d_l___color.html", null ],
    [ "SDL_CommonEvent", "struct_s_d_l___common_event.html", null ],
    [ "SDL_ControllerAxisEvent", "struct_s_d_l___controller_axis_event.html", null ],
    [ "SDL_ControllerButtonEvent", "struct_s_d_l___controller_button_event.html", null ],
    [ "SDL_ControllerDeviceEvent", "struct_s_d_l___controller_device_event.html", null ],
    [ "SDL_ControllerSensorEvent", "struct_s_d_l___controller_sensor_event.html", null ],
    [ "SDL_ControllerTouchpadEvent", "struct_s_d_l___controller_touchpad_event.html", null ],
    [ "SDL_DisplayEvent", "struct_s_d_l___display_event.html", null ],
    [ "SDL_DisplayMode", "struct_s_d_l___display_mode.html", null ],
    [ "SDL_DollarGestureEvent", "struct_s_d_l___dollar_gesture_event.html", null ],
    [ "SDL_DropEvent", "struct_s_d_l___drop_event.html", null ],
    [ "SDL_Event", "union_s_d_l___event.html", null ],
    [ "SDL_Finger", "struct_s_d_l___finger.html", null ],
    [ "SDL_FPoint", "struct_s_d_l___f_point.html", null ],
    [ "SDL_FRect", "struct_s_d_l___f_rect.html", null ],
    [ "SDL_GameControllerButtonBind", "struct_s_d_l___game_controller_button_bind.html", null ],
    [ "SDL_HapticCondition", "struct_s_d_l___haptic_condition.html", null ],
    [ "SDL_HapticConstant", "struct_s_d_l___haptic_constant.html", null ],
    [ "SDL_HapticCustom", "struct_s_d_l___haptic_custom.html", null ],
    [ "SDL_HapticDirection", "struct_s_d_l___haptic_direction.html", null ],
    [ "SDL_HapticEffect", "union_s_d_l___haptic_effect.html", null ],
    [ "SDL_HapticLeftRight", "struct_s_d_l___haptic_left_right.html", null ],
    [ "SDL_HapticPeriodic", "struct_s_d_l___haptic_periodic.html", null ],
    [ "SDL_HapticRamp", "struct_s_d_l___haptic_ramp.html", null ],
    [ "SDL_hid_device_info", "struct_s_d_l__hid__device__info.html", null ],
    [ "SDL_JoyAxisEvent", "struct_s_d_l___joy_axis_event.html", null ],
    [ "SDL_JoyBallEvent", "struct_s_d_l___joy_ball_event.html", null ],
    [ "SDL_JoyButtonEvent", "struct_s_d_l___joy_button_event.html", null ],
    [ "SDL_JoyDeviceEvent", "struct_s_d_l___joy_device_event.html", null ],
    [ "SDL_JoyHatEvent", "struct_s_d_l___joy_hat_event.html", null ],
    [ "SDL_JoystickGUID", "struct_s_d_l___joystick_g_u_i_d.html", null ],
    [ "SDL_KeyboardEvent", "struct_s_d_l___keyboard_event.html", null ],
    [ "SDL_Keysym", "struct_s_d_l___keysym.html", null ],
    [ "SDL_Locale", "struct_s_d_l___locale.html", null ],
    [ "SDL_MessageBoxButtonData", "struct_s_d_l___message_box_button_data.html", null ],
    [ "SDL_MessageBoxColor", "struct_s_d_l___message_box_color.html", null ],
    [ "SDL_MessageBoxColorScheme", "struct_s_d_l___message_box_color_scheme.html", null ],
    [ "SDL_MessageBoxData", "struct_s_d_l___message_box_data.html", null ],
    [ "SDL_MouseButtonEvent", "struct_s_d_l___mouse_button_event.html", null ],
    [ "SDL_MouseMotionEvent", "struct_s_d_l___mouse_motion_event.html", null ],
    [ "SDL_MouseWheelEvent", "struct_s_d_l___mouse_wheel_event.html", null ],
    [ "SDL_MultiGestureEvent", "struct_s_d_l___multi_gesture_event.html", null ],
    [ "SDL_OSEvent", "struct_s_d_l___o_s_event.html", null ],
    [ "SDL_Palette", "struct_s_d_l___palette.html", null ],
    [ "SDL_PixelFormat", "struct_s_d_l___pixel_format.html", null ],
    [ "SDL_Point", "struct_s_d_l___point.html", null ],
    [ "SDL_QuitEvent", "struct_s_d_l___quit_event.html", null ],
    [ "SDL_Rect", "struct_s_d_l___rect.html", null ],
    [ "SDL_RendererInfo", "struct_s_d_l___renderer_info.html", null ],
    [ "SDL_RWops", "struct_s_d_l___r_wops.html", null ],
    [ "SDL_SensorEvent", "struct_s_d_l___sensor_event.html", null ],
    [ "SDL_Surface", "struct_s_d_l___surface.html", null ],
    [ "SDL_SysWMEvent", "struct_s_d_l___sys_w_m_event.html", null ],
    [ "SDL_SysWMinfo", "struct_s_d_l___sys_w_minfo.html", null ],
    [ "SDL_SysWMmsg", "struct_s_d_l___sys_w_mmsg.html", null ],
    [ "SDL_TextEditingEvent", "struct_s_d_l___text_editing_event.html", null ],
    [ "SDL_TextInputEvent", "struct_s_d_l___text_input_event.html", null ],
    [ "SDL_TouchFingerEvent", "struct_s_d_l___touch_finger_event.html", null ],
    [ "SDL_UserEvent", "struct_s_d_l___user_event.html", null ],
    [ "SDL_version", "struct_s_d_l__version.html", null ],
    [ "SDL_Vertex", "struct_s_d_l___vertex.html", null ],
    [ "SDL_WindowEvent", "struct_s_d_l___window_event.html", null ],
    [ "SDL_WindowShapeMode", "struct_s_d_l___window_shape_mode.html", null ],
    [ "SDL_WindowShapeParams", "union_s_d_l___window_shape_params.html", null ],
    [ "SDLTest_CommonState", "struct_s_d_l_test___common_state.html", null ],
    [ "SDLTest_Crc32Context", "struct_s_d_l_test___crc32_context.html", null ],
    [ "SDLTest_Md5Context", "struct_s_d_l_test___md5_context.html", null ],
    [ "SDLTest_RandomContext", "struct_s_d_l_test___random_context.html", null ],
    [ "SDLTest_SurfaceImage_s", "struct_s_d_l_test___surface_image__s.html", null ],
    [ "SDLTest_TestCaseReference", "struct_s_d_l_test___test_case_reference.html", null ],
    [ "SDLTest_TestSuiteReference", "struct_s_d_l_test___test_suite_reference.html", null ],
    [ "RT::Texture::TextureBase", "class_r_t_1_1_texture_1_1_texture_base.html", [
      [ "RT::Texture::Checker", "class_r_t_1_1_texture_1_1_checker.html", null ],
      [ "RT::Texture::Flat", "class_r_t_1_1_texture_1_1_flat.html", null ],
      [ "RT::Texture::Image", "class_r_t_1_1_texture_1_1_image.html", null ]
    ] ]
];