.TH "D:/RayTracing/include/begin_code.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/include/begin_code.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_begin_code_h\fP"
.br
.ti -1c
.RI "#define \fBSDL_DEPRECATED\fP"
.br
.ti -1c
.RI "#define \fBSDL_UNUSED\fP"
.br
.ti -1c
.RI "#define \fBDECLSPEC\fP"
.br
.ti -1c
.RI "#define \fBSDLCALL\fP"
.br
.ti -1c
.RI "#define \fBSDL_INLINE\fP   inline"
.br
.ti -1c
.RI "#define \fB__inline__\fP   inline"
.br
.ti -1c
.RI "#define \fBSDL_FORCE_INLINE\fP   static \fBSDL_INLINE\fP"
.br
.ti -1c
.RI "#define \fBSDL_NORETURN\fP"
.br
.ti -1c
.RI "#define \fBNULL\fP   ((\fBvoid\fP *)0)"
.br
.ti -1c
.RI "#define \fB_HAS_FALLTHROUGH\fP   0"
.br
.ti -1c
.RI "#define \fBSDL_FALLTHROUGH\fP   do {} while (0) /* fallthrough */"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file sets things up for C dynamic library function definitions, static inlined functions, and structures aligned at 4-byte alignment\&. If you don't like ugly C preprocessor code, don't look at this file\&. :) 
.SH "Macro Definition Documentation"
.PP 
.SS "#define __inline__   inline"

.SS "#define _begin_code_h"

.SS "#define _HAS_FALLTHROUGH   0"

.SS "#define DECLSPEC"

.SS "#define NULL   ((\fBvoid\fP *)0)"

.SS "#define SDL_DEPRECATED"

.SS "#define SDL_FALLTHROUGH   do {} while (0) /* fallthrough */"

.SS "#define SDL_FORCE_INLINE   static \fBSDL_INLINE\fP"

.SS "#define SDL_INLINE   inline"

.SS "#define SDL_NORETURN"

.SS "#define SDL_UNUSED"

.SS "#define SDLCALL"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
