.TH "CApp" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CApp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CApp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCApp\fP ()"
.br
.ti -1c
.RI "int \fBOnExecute\fP ()"
.br
.ti -1c
.RI "bool \fBOnInit\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnEvent\fP (\fBSDL_Event\fP *\fBevent\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnLoop\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnRender\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnExit\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CApp::CApp ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP CApp::OnEvent (\fBSDL_Event\fP * event)"

.SS "int CApp::OnExecute ()"

.SS "\fBvoid\fP CApp::OnExit ()"

.SS "bool CApp::OnInit ()"
Test renderowania tekstury (należy zakomentować renderowanie sceny powyżej)^
.SS "\fBvoid\fP CApp::OnLoop ()"

.SS "\fBvoid\fP CApp::OnRender ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
