.TH "D:/RayTracing/RayTrace/Primitives Directory Reference" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/RayTrace/Primitives Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcone\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcone\&.h\fP"
.br
.ti -1c
.RI "file \fBcylinder\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcylinder\&.h\fP"
.br
.ti -1c
.RI "file \fBobjectbase\&.cpp\fP"
.br
.ti -1c
.RI "file \fBobjectbase\&.h\fP"
.br
.ti -1c
.RI "file \fBobjplane\&.cpp\fP"
.br
.ti -1c
.RI "file \fBobjplane\&.h\fP"
.br
.ti -1c
.RI "file \fBobjsphere\&.cpp\fP"
.br
.ti -1c
.RI "file \fBobjsphere\&.h\fP"
.br
.in -1c
