.TH "D:/RayTracing/RayTrace Directory Reference" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/RayTrace Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBLights\fP"
.br
.ti -1c
.RI "directory \fBMaterials\fP"
.br
.ti -1c
.RI "directory \fBPrimitives\fP"
.br
.ti -1c
.RI "directory \fBqbLinAlg\fP"
.br
.ti -1c
.RI "directory \fBTextures\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcamera\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcamera\&.h\fP"
.br
.ti -1c
.RI "file \fBgtfm\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgtfm\&.h\fP"
.br
.ti -1c
.RI "file \fBImage\&.cpp\fP"
.br
.ti -1c
.RI "file \fBImage\&.h\fP"
.br
.ti -1c
.RI "file \fBray\&.cpp\fP"
.br
.ti -1c
.RI "file \fBray\&.h\fP"
.br
.ti -1c
.RI "file \fBScene\&.cpp\fP"
.br
.ti -1c
.RI "file \fBScene\&.h\fP"
.br
.in -1c
