.TH "D:/RayTracing Directory Reference" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcmake\-build\-debug\fP"
.br
.ti -1c
.RI "directory \fBdocs\fP"
.br
.ti -1c
.RI "directory \fBinclude\fP"
.br
.ti -1c
.RI "directory \fBRayTrace\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCApp\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCApp\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
