.TH "D:/RayTracing/RayTrace/qbLinAlg Directory Reference" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/RayTrace/qbLinAlg Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBqbEIG\&.h\fP"
.br
.ti -1c
.RI "file \fBqbLinSolve\&.h\fP"
.br
.ti -1c
.RI "file \fBqbLSQ\&.h\fP"
.br
.ti -1c
.RI "file \fBqbMatrix\&.h\fP"
.br
.ti -1c
.RI "file \fBqbPCA\&.h\fP"
.br
.ti -1c
.RI "file \fBqbQR\&.h\fP"
.br
.ti -1c
.RI "file \fBqbVector\&.h\fP"
.br
.in -1c
