.TH "D:/RayTracing/RayTrace/Lights Directory Reference" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/RayTrace/Lights Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlightbase\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlightbase\&.h\fP"
.br
.ti -1c
.RI "file \fBpointlight\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpointlight\&.h\fP"
.br
.in -1c
