.TH "deprecated" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBMember \fBSDL_GetRevisionNumber\fP (void)\fP" 1c
Use \fBSDL_GetRevision()\fP instead; if SDL was carefully built, it will return a git hash\&. 
.IP "\fBFile \fBSDL_types\&.h\fP \fP" 1c
 
.PP

