.TH "D:/RayTracing/RayTrace/Textures/flat.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/RayTrace/Textures/flat.h
.SH SYNOPSIS
.br
.PP
\fC#include 'texturebase\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRT::Texture::Flat\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRT\fP"
.br
.ti -1c
.RI "namespace \fBRT::Texture\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
