.TH "D:/RayTracing/RayTrace/gtfm.cpp" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/RayTrace/gtfm.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'gtfm\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRT\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRT::GTform\fP \fBRT::operator*\fP (const \fBRT::GTform\fP &lhs, const \fBRT::GTform\fP &rhs)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
