.TH "D:/RayTracing/RayTrace/gtfm.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/RayTrace/gtfm.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&./qbLinAlg/qbVector\&.h'\fP
.br
\fC#include '\&./qbLinAlg/qbMatrix\&.h'\fP
.br
\fC#include 'ray\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRT::GTform\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRT\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr bool \fBRT::FWDTFORM\fP = true"
.br
.ti -1c
.RI "constexpr bool \fBRT::BCKTFORM\fP = false"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
