.TH "D:/RayTracing/RayTrace/Lights/lightbase.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/RayTrace/Lights/lightbase.h
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include '\&.\&./qbLinAlg/qbVector\&.h'\fP
.br
\fC#include '\&.\&./ray\&.h'\fP
.br
\fC#include '\&.\&./Primitives/objectbase\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRT::LightBase\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRT\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
