.TH "md__d___ray_tracing_docs__r_e_a_d_m_e_gesture" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__d___ray_tracing_docs__r_e_a_d_m_e_gesture \- Dollar Gestures 
SDL provides an implementation of the $1 gesture recognition system\&. This allows for recording, saving, loading, and performing single stroke gestures\&.
.PP
Gestures can be performed with any number of fingers (the centroid of the fingers must follow the path of the gesture), but the number of fingers must be constant (a finger cannot go down in the middle of a gesture)\&. The path of a gesture is considered the path from the time when the final finger went down, to the first time any finger comes up\&.
.PP
Dollar gestures are assigned an Id based on a hash function\&. This is guaranteed to remain constant for a given gesture\&. There is a (small) chance that two different gestures will be assigned the same ID\&. In this case, simply re-recording one of the gestures should result in a different ID\&.
.SH "Recording:"
.PP
To begin recording on a touch device call: \fBSDL_RecordGesture(SDL_TouchID touchId)\fP, where touchId is the id of the touch device you wish to record on, or -1 to record on all connected devices\&.
.PP
Recording terminates as soon as a finger comes up\&. Recording is acknowledged by an SDL_DOLLARRECORD event\&. A SDL_DOLLARRECORD event is a dgesture with the following fields:
.PP
.IP "\(bu" 2
event\&.dgesture\&.touchId - the Id of the touch used to record the gesture\&.
.IP "\(bu" 2
event\&.dgesture\&.gestureId - the unique id of the recorded gesture\&.
.PP
.SH "Performing:"
.PP
As long as there is a dollar gesture assigned to a touch, every finger-up event will also cause an SDL_DOLLARGESTURE event with the following fields:
.PP
.IP "\(bu" 2
event\&.dgesture\&.touchId - the Id of the touch which performed the gesture\&.
.IP "\(bu" 2
event\&.dgesture\&.gestureId - the unique id of the closest gesture to the performed stroke\&.
.IP "\(bu" 2
event\&.dgesture\&.error - the difference between the gesture template and the actual performed gesture\&. Lower error is a better match\&.
.IP "\(bu" 2
event\&.dgesture\&.numFingers - the number of fingers used to draw the stroke\&.
.PP
.PP
Most programs will want to define an appropriate error threshold and check to be sure that the error of a gesture is not abnormally high (an indicator that no gesture was performed)\&.
.SH "Saving:"
.PP
To save a template, call SDL_SaveDollarTemplate(gestureId, dst) where gestureId is the id of the gesture you want to save, and dst is an \fBSDL_RWops\fP pointer to the file where the gesture will be stored\&.
.PP
To save all currently loaded templates, call SDL_SaveAllDollarTemplates(dst) where dst is an \fBSDL_RWops\fP pointer to the file where the gesture will be stored\&.
.PP
Both functions return the number of gestures successfully saved\&.
.SH "Loading:"
.PP
To load templates from a file, call SDL_LoadDollarTemplates(touchId,src) where touchId is the id of the touch to load to (or -1 to load to all touch devices), and src is an \fBSDL_RWops\fP pointer to a gesture save file\&.
.PP
SDL_LoadDollarTemplates returns the number of templates successfully loaded\&.
.PP
.PP
 
.SH "Multi Gestures"
.PP
SDL provides simple support for pinch/rotate/swipe gestures\&. Every time a finger is moved an SDL_MULTIGESTURE event is sent with the following fields:
.PP
.IP "\(bu" 2
event\&.mgesture\&.touchId - the Id of the touch on which the gesture was performed\&.
.IP "\(bu" 2
event\&.mgesture\&.x - the normalized x coordinate of the gesture\&. (0\&.\&.1)
.IP "\(bu" 2
event\&.mgesture\&.y - the normalized y coordinate of the gesture\&. (0\&.\&.1)
.IP "\(bu" 2
event\&.mgesture\&.dTheta - the amount that the fingers rotated during this motion\&.
.IP "\(bu" 2
event\&.mgesture\&.dDist - the amount that the fingers pinched during this motion\&.
.IP "\(bu" 2
event\&.mgesture\&.numFingers - the number of fingers used in the gesture\&.
.PP
.PP
.PP
 
.SH "Notes"
.PP
For a complete example see test/testgesture\&.c
.PP
Please direct questions/comments to: jim.tla+sdl_touch@gmail.com 
