.TH "md__d___ray_tracing_docs__r_e_a_d_m_e_psp" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__d___ray_tracing_docs__r_e_a_d_m_e_psp \- PSP 
SDL port for the Sony PSP contributed by Captian Lex
.PP
Credit to Marcus R\&.Brown,Jim Paris,Matthew H for the original SDL 1\&.2 for PSP Geecko for his PSP GU lib 'Glib2d'
.SH "Building"
.PP
To build SDL2 library for the PSP, make sure psp-config is in the path and run: make -f Makefile\&.psp
.SH "Getting PSP toolchain"
.PP
https://github.com/pspdev/psptoolchain
.SH "Running on PPSSPP Emulator"
.PP
https://github.com/hrydgard/ppsspp ( https://github.com/hrydgard/ppsspp/wiki/Build-instructions )
.SH "Compiling an HelloWorld"
.PP
https://psp-dev.org/doku.php?id=tutorial:hello_world
.SH "To Do"
.PP
PSP Screen Keyboard 
