.TH "md__d___ray_tracing_docs__r_e_a_d_m_e_git" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__d___ray_tracing_docs__r_e_a_d_m_e_git \- git 
The latest development version of SDL is available via git\&. Git allows you to get up-to-the-minute fixes and enhancements; as a developer works on a source tree, you can use 'git' to mirror that source tree instead of waiting for an official release\&. Please look at the Git website ( https://git-scm.com/ ) for more information on using git, where you can also download software for macOS, Windows, and Unix systems\&. 
.PP
.nf
git clone https://github\&.com/libsdl-org/SDL

.fi
.PP
 If you are building SDL via configure, you will need to run autogen\&.sh before running configure\&.
.PP
There is a web interface to the Git repository at: http://github.com/libsdl-org/SDL/ 
