.TH "md__d___ray_tracing_docs__r_e_a_d_m_e_platforms" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__d___ray_tracing_docs__r_e_a_d_m_e_platforms \- Platforms 
We maintain the list of supported platforms on our wiki now, and how to build and install SDL for those platforms: 
.PP
.nf
https://wiki\&.libsdl\&.org/Installation

.fi
.PP
 
