.TH "md__d___ray_tracing_docs__r_e_a_d_m_e_wince" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__d___ray_tracing_docs__r_e_a_d_m_e_wince \- WinCE 
Windows CE is no longer supported by SDL\&.
.PP
We have left the CE support in SDL 1\&.2 for those that must have it, and we have support for Windows Phone 8 and WinRT in SDL2, as of SDL 2\&.0\&.3\&.
.PP
--ryan\&. 
