.TH "D:/RayTracing/RayTrace/Lights/pointlight.cpp" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/RayTrace/Lights/pointlight.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'pointlight\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
