.TH "D:/RayTracing/RayTrace/qbLinAlg/qbQR.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/RayTrace/qbLinAlg/qbQR.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdexcept>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'qbMatrix\&.h'\fP
.br
\fC#include 'qbVector\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > int \fBqbQR\fP (const \fBqbMatrix2\fP< T > &A, \fBqbMatrix2\fP< T > &Q, \fBqbMatrix2\fP< T > &R)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr int \fBQBQR_MATRIXNOTSQUARE\fP = \-1"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > int qbQR (const \fBqbMatrix2\fP< T > & A, \fBqbMatrix2\fP< T > & Q, \fBqbMatrix2\fP< T > & R)"

.SH "Variable Documentation"
.PP 
.SS "constexpr int QBQR_MATRIXNOTSQUARE = \-1\fC [constexpr]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
