.TH "RT" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RT
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTexture\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCamera\fP"
.br
.ti -1c
.RI "class \fBCone\fP"
.br
.ti -1c
.RI "class \fBCylinder\fP"
.br
.ti -1c
.RI "class \fBGTform\fP"
.br
.ti -1c
.RI "class \fBLightBase\fP"
.br
.ti -1c
.RI "class \fBMaterialBase\fP"
.br
.ti -1c
.RI "class \fBObjectBase\fP"
.br
.ti -1c
.RI "class \fBObjPlane\fP"
.br
.ti -1c
.RI "class \fBObjSphere\fP"
.br
.ti -1c
.RI "class \fBPointLight\fP"
.br
.ti -1c
.RI "class \fBRay\fP"
.br
.ti -1c
.RI "class \fBScene\fP"
.br
.ti -1c
.RI "class \fBSimpleMaterial\fP"
.br
.ti -1c
.RI "class \fBSimpleRefractive\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRT::GTform\fP \fBoperator*\fP (const \fBRT::GTform\fP &lhs, const \fBRT::GTform\fP &rhs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr bool \fBFWDTFORM\fP = true"
.br
.ti -1c
.RI "constexpr bool \fBBCKTFORM\fP = false"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBRT::GTform\fP RT::operator* (const \fBRT::GTform\fP & lhs, const \fBRT::GTform\fP & rhs)"

.SH "Variable Documentation"
.PP 
.SS "constexpr bool RT::BCKTFORM = false\fC [constexpr]\fP"

.SS "constexpr bool RT::FWDTFORM = true\fC [constexpr]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
