.TH "RT::Cone" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RT::Cone
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cone\&.h>\fP
.PP
Inherits \fBRT::ObjectBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCone\fP ()"
.br
.ti -1c
.RI "virtual \fB~Cone\fP () override"
.br
.ti -1c
.RI "virtual bool \fBTestIntersection\fP (const \fBRT::Ray\fP &castRay, \fBqbVector\fP< double > &intPoint, \fBqbVector\fP< double > &localNormal, \fBqbVector\fP< double > &localColor) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RT::Cone::Cone ()"

.SS "RT::Cone::~Cone ()\fC [override]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool RT::Cone::TestIntersection (const \fBRT::Ray\fP & castRay, \fBqbVector\fP< double > & intPoint, \fBqbVector\fP< double > & localNormal, \fBqbVector\fP< double > & localColor)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBRT::ObjectBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
