.TH "RT::Texture" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RT::Texture
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChecker\fP"
.br
.ti -1c
.RI "class \fBFlat\fP"
.br
.ti -1c
.RI "class \fBImage\fP"
.br
.ti -1c
.RI "class \fBTextureBase\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
