.TH "D:/RayTracing/RayTrace/Scene.cpp" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/RayTrace/Scene.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Scene\&.h'\fP
.br
\fC#include '\&./Materials/simplematerial\&.h'\fP
.br
\fC#include '\&./Textures/checker\&.h'\fP
.br
\fC#include 'Textures/textureimage\&.h'\fP
.br
\fC#include 'Materials/simplerefractive\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
