.TH "D:/RayTracing/include/SDL_test_images.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/include/SDL_test_images.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL\&.h'\fP
.br
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSDLTest_SurfaceImage_s\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBSDLTest_SurfaceImage_s\fP \fBSDLTest_SurfaceImage_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlit\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitColor\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitAlpha\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlendAdd\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlend\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlendMod\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlendNone\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlendAll\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageFace\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImagePrimitives\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImagePrimitivesBlend\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include file for SDL test framework\&.
.PP
This code is a part of the SDL2_test library, not the main SDL library\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBSDLTest_SurfaceImage_s\fP \fBSDLTest_SurfaceImage_t\fP"
Type for test images\&. 
.SH "Function Documentation"
.PP 
.SS "\fBSDL_Surface\fP * SDLTest_ImageBlit (\fBvoid\fP)"

.SS "\fBSDL_Surface\fP * SDLTest_ImageBlitAlpha (\fBvoid\fP)"

.SS "\fBSDL_Surface\fP * SDLTest_ImageBlitBlend (\fBvoid\fP)"

.SS "\fBSDL_Surface\fP * SDLTest_ImageBlitBlendAdd (\fBvoid\fP)"

.SS "\fBSDL_Surface\fP * SDLTest_ImageBlitBlendAll (\fBvoid\fP)"

.SS "\fBSDL_Surface\fP * SDLTest_ImageBlitBlendMod (\fBvoid\fP)"

.SS "\fBSDL_Surface\fP * SDLTest_ImageBlitBlendNone (\fBvoid\fP)"

.SS "\fBSDL_Surface\fP * SDLTest_ImageBlitColor (\fBvoid\fP)"

.SS "\fBSDL_Surface\fP * SDLTest_ImageFace (\fBvoid\fP)"

.SS "\fBSDL_Surface\fP * SDLTest_ImagePrimitives (\fBvoid\fP)"

.SS "\fBSDL_Surface\fP * SDLTest_ImagePrimitivesBlend (\fBvoid\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
