.TH "SDL_OSEvent" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_OSEvent \- OS Specific event\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUint32\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBtimestamp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
OS Specific event\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBUint32\fP SDL_OSEvent::timestamp"
In milliseconds, populated using \fBSDL_GetTicks()\fP 
.SS "\fBUint32\fP SDL_OSEvent::type"
\fBSDL_QUIT\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
