.TH "SDL_version" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_version
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_version\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUint8\fP \fBmajor\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBminor\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBpatch\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information about the version of SDL in use\&.
.PP
Represents the library's version as three levels: major revision (increments with massive changes, additions, and enhancements), minor revision (increments with backwards-compatible changes to the major revision), and patchlevel (increments with fixes to the minor revision)\&.
.PP
\fBSee also\fP
.RS 4
\fBSDL_VERSION\fP 
.PP
\fBSDL_GetVersion\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBUint8\fP SDL_version::major"
major version 
.SS "\fBUint8\fP SDL_version::minor"
minor version 
.SS "\fBUint8\fP SDL_version::patch"
update version 

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
