.TH "SDL_Color" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Color
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_pixels\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUint8\fP \fBr\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBg\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBb\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The bits of this structure can be directly reinterpreted as an integer-packed color which uses the SDL_PIXELFORMAT_RGBA32 format (SDL_PIXELFORMAT_ABGR8888 on little-endian systems and SDL_PIXELFORMAT_RGBA8888 on big-endian systems)\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBUint8\fP SDL_Color::a"

.SS "\fBUint8\fP SDL_Color::b"

.SS "\fBUint8\fP SDL_Color::g"

.SS "\fBUint8\fP SDL_Color::r"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
