.TH "D:/RayTracing/include/SDL_revision.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/include/SDL_revision.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDL_REVISION\fP   'https://github\&.com/libsdl\-org/SDL\&.git@b424665e0899769b200231ba943353a5fee1b6b6'"
.br
.ti -1c
.RI "#define \fBSDL_REVISION_NUMBER\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SDL_REVISION   'https://github\&.com/libsdl\-org/SDL\&.git@b424665e0899769b200231ba943353a5fee1b6b6'"

.SS "#define SDL_REVISION_NUMBER   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
