.TH "SDL_MessageBoxColor" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MessageBoxColor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_messagebox\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUint8\fP \fBr\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBg\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RGB value used in a message box color scheme 
.SH "Member Data Documentation"
.PP 
.SS "\fBUint8\fP SDL_MessageBoxColor::b"

.SS "\fBUint8\fP SDL_MessageBoxColor::g"

.SS "\fBUint8\fP SDL_MessageBoxColor::r"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
