.TH "SDL_Palette" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Palette
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_pixels\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBncolors\fP"
.br
.ti -1c
.RI "\fBSDL_Color\fP * \fBcolors\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBversion\fP"
.br
.ti -1c
.RI "int \fBrefcount\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBSDL_Color\fP* SDL_Palette::colors"

.SS "int SDL_Palette::ncolors"

.SS "int SDL_Palette::refcount"

.SS "\fBUint32\fP SDL_Palette::version"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
