.TH "D:/RayTracing/include/SDL_test_font.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/include/SDL_test_font.h
.SH SYNOPSIS
.br
.PP
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFONT_CHARACTER_SIZE\fP   8"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBSDLTest_DrawCharacter\fP (\fBSDL_Renderer\fP *renderer, int \fBx\fP, int \fBy\fP, char \fBc\fP)"
.br
.RI "Draw a string in the currently set font\&. "
.ti -1c
.RI "int \fBSDLTest_DrawString\fP (\fBSDL_Renderer\fP *renderer, int \fBx\fP, int \fBy\fP, const char *\fBs\fP)"
.br
.RI "Draw a string in the currently set font\&. "
.ti -1c
.RI "\fBvoid\fP \fBSDLTest_CleanupTextDrawing\fP (\fBvoid\fP)"
.br
.RI "Cleanup textures used by font drawing functions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Include file for SDL test framework\&.
.PP
This code is a part of the SDL2_test library, not the main SDL library\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define FONT_CHARACTER_SIZE   8"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP SDLTest_CleanupTextDrawing (\fBvoid\fP)"

.PP
Cleanup textures used by font drawing functions\&. 
.SS "int SDLTest_DrawCharacter (\fBSDL_Renderer\fP * renderer, int x, int y, char c)"

.PP
Draw a string in the currently set font\&. 
.PP
\fBParameters\fP
.RS 4
\fIrenderer\fP The renderer to draw on\&. 
.br
\fIx\fP The X coordinate of the upper left corner of the character\&. 
.br
\fIy\fP The Y coordinate of the upper left corner of the character\&. 
.br
\fIc\fP The character to draw\&.
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 on failure\&. 
.RE
.PP

.SS "int SDLTest_DrawString (\fBSDL_Renderer\fP * renderer, int x, int y, const char * s)"

.PP
Draw a string in the currently set font\&. 
.PP
\fBParameters\fP
.RS 4
\fIrenderer\fP The renderer to draw on\&. 
.br
\fIx\fP The X coordinate of the upper left corner of the string\&. 
.br
\fIy\fP The Y coordinate of the upper left corner of the string\&. 
.br
\fIs\fP The string to draw\&.
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 on failure\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
