.TH "SDL_MessageBoxColorScheme" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MessageBoxColorScheme
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_messagebox\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSDL_MessageBoxColor\fP \fBcolors\fP [\fBSDL_MESSAGEBOX_COLOR_MAX\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
A set of colors to use for message box dialogs 
.SH "Member Data Documentation"
.PP 
.SS "\fBSDL_MessageBoxColor\fP SDL_MessageBoxColorScheme::colors[\fBSDL_MESSAGEBOX_COLOR_MAX\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
