.TH "D:/RayTracing/include/SDL_config.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/include/SDL_config.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL_platform\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDL_config_h_\fP"
.br
.ti -1c
.RI "#define \fB_SIZE_T_DEFINED_\fP"
.br
.ti -1c
.RI "#define \fBSIZEOF_VOIDP\fP   4"
.br
.ti -1c
.RI "#define \fBHAVE_DDRAW_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_DINPUT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_DSOUND_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_DXGI_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_XINPUT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MMDEVICEAPI_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_AUDIOCLIENT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_TPCSHRD_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SENSORSAPI_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDARG_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDDEF_H\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_WASAPI\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_DSOUND\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_WINMM\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_DISK\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_JOYSTICK_DINPUT\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_JOYSTICK_HIDAPI\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_JOYSTICK_RAWINPUT\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_JOYSTICK_VIRTUAL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_JOYSTICK_XINPUT\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_HAPTIC_DINPUT\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_HAPTIC_XINPUT\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_SENSOR_WINDOWS\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_LOADSO_WINDOWS\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_THREAD_GENERIC_COND_SUFFIX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_THREAD_WINDOWS\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_TIMER_WINDOWS\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_WINDOWS\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_RENDER_D3D\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_WGL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_RENDER_OGL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_RENDER_OGL_ES2\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_ES2\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_EGL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_VULKAN\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_POWER_WINDOWS\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_FILESYSTEM_WINDOWS\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_ASSEMBLY_ROUTINES\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef signed char \fBint8_t\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuint8_t\fP"
.br
.ti -1c
.RI "typedef signed short \fBint16_t\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBuint16_t\fP"
.br
.ti -1c
.RI "typedef signed int \fBint32_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBuint32_t\fP"
.br
.ti -1c
.RI "typedef signed long long \fBint64_t\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBuint64_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBsize_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBuintptr_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _SIZE_T_DEFINED_"

.SS "#define HAVE_AUDIOCLIENT_H   1"

.SS "#define HAVE_DDRAW_H   1"

.SS "#define HAVE_DINPUT_H   1"

.SS "#define HAVE_DSOUND_H   1"

.SS "#define HAVE_DXGI_H   1"

.SS "#define HAVE_MMDEVICEAPI_H   1"

.SS "#define HAVE_SENSORSAPI_H   1"

.SS "#define HAVE_STDARG_H   1"

.SS "#define HAVE_STDDEF_H   1"

.SS "#define HAVE_TPCSHRD_H   1"

.SS "#define HAVE_XINPUT_H   1"

.SS "#define SDL_ASSEMBLY_ROUTINES   1"

.SS "#define SDL_AUDIO_DRIVER_DISK   1"

.SS "#define SDL_AUDIO_DRIVER_DSOUND   1"

.SS "#define SDL_AUDIO_DRIVER_DUMMY   1"

.SS "#define SDL_AUDIO_DRIVER_WASAPI   1"

.SS "#define SDL_AUDIO_DRIVER_WINMM   1"

.SS "#define SDL_config_h_"

.SS "#define SDL_FILESYSTEM_WINDOWS   1"

.SS "#define SDL_HAPTIC_DINPUT   1"

.SS "#define SDL_HAPTIC_XINPUT   1"

.SS "#define SDL_JOYSTICK_DINPUT   1"

.SS "#define SDL_JOYSTICK_HIDAPI   1"

.SS "#define SDL_JOYSTICK_RAWINPUT   1"

.SS "#define SDL_JOYSTICK_VIRTUAL   1"

.SS "#define SDL_JOYSTICK_XINPUT   1"

.SS "#define SDL_LOADSO_WINDOWS   1"

.SS "#define SDL_POWER_WINDOWS   1"

.SS "#define SDL_SENSOR_WINDOWS   1"

.SS "#define SDL_THREAD_GENERIC_COND_SUFFIX   1"

.SS "#define SDL_THREAD_WINDOWS   1"

.SS "#define SDL_TIMER_WINDOWS   1"

.SS "#define SDL_VIDEO_DRIVER_DUMMY   1"

.SS "#define SDL_VIDEO_DRIVER_WINDOWS   1"

.SS "#define SDL_VIDEO_OPENGL   1"

.SS "#define SDL_VIDEO_OPENGL_EGL   1"

.SS "#define SDL_VIDEO_OPENGL_ES2   1"

.SS "#define SDL_VIDEO_OPENGL_WGL   1"

.SS "#define SDL_VIDEO_RENDER_D3D   1"

.SS "#define SDL_VIDEO_RENDER_OGL   1"

.SS "#define SDL_VIDEO_RENDER_OGL_ES2   1"

.SS "#define SDL_VIDEO_VULKAN   1"

.SS "#define SIZEOF_VOIDP   4"

.SH "Typedef Documentation"
.PP 
.SS "typedef signed short \fBint16_t\fP"

.SS "typedef signed int \fBint32_t\fP"

.SS "typedef signed long long \fBint64_t\fP"

.SS "typedef signed char \fBint8_t\fP"

.SS "typedef unsigned int \fBsize_t\fP"

.SS "typedef unsigned short \fBuint16_t\fP"

.SS "typedef unsigned int \fBuint32_t\fP"

.SS "typedef unsigned long long \fBuint64_t\fP"

.SS "typedef unsigned char \fBuint8_t\fP"

.SS "typedef unsigned int \fBuintptr_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
