.TH "D:/RayTracing/include/SDL_config_psp.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/include/SDL_config_psp.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL_platform\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDL_config_h_\fP"
.br
.ti -1c
.RI "#define \fBHAVE_GCC_ATOMICS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ALLOCA_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDIO_H\fP   1"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CTYPE_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MATH_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIGNAL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_REALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FREE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ALLOCA\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_GETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_PUTENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNSETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_QSORT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ABS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_BCOPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMSET\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMMOVE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRLEN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRLCPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRLCAT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRDUP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCHR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRRCHR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRSTR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOUL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOLL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOULL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOD\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATOI\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATOF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRNCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCASECMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRNCASECMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_VSSCANF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_VSNPRINTF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_M_PI\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATAN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATAN2\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ACOS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ASIN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CEIL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COPYSIGN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COSF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FABS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FLOOR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LOG\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_POW\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SCALBN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SINF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SQRT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SQRTF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_TAN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_TANF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SETJMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_NANOSLEEP\fP   1"
.br
.ti -1c
.RI "#define \fBLACKS_SYS_MMAN_H\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_THREAD_PSP\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_TIMERS_PSP\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_JOYSTICK_PSP\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_PSP\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_PSP\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_RENDER_PSP\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_POWER_PSP\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_FILESYSTEM_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_HAPTIC_DISABLED\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_LOADSO_DISABLED\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HAVE_ABS   1"

.SS "#define HAVE_ACOS   1"

.SS "#define HAVE_ALLOCA   1"

.SS "#define HAVE_ALLOCA_H   1"

.SS "#define HAVE_ASIN   1"

.SS "#define HAVE_ATAN   1"

.SS "#define HAVE_ATAN2   1"

.SS "#define HAVE_ATOF   1"

.SS "#define HAVE_ATOI   1"

.SS "#define HAVE_BCOPY   1"

.SS "#define HAVE_CALLOC   1"

.SS "#define HAVE_CEIL   1"

.SS "#define HAVE_COPYSIGN   1"

.SS "#define HAVE_COS   1"

.SS "#define HAVE_COSF   1"

.SS "#define HAVE_CTYPE_H   1"

.SS "#define HAVE_FABS   1"

.SS "#define HAVE_FLOOR   1"

.SS "#define HAVE_FREE   1"

.SS "#define HAVE_GCC_ATOMICS   1"

.SS "#define HAVE_GETENV   1"

.SS "#define HAVE_INTTYPES_H   1"

.SS "#define HAVE_LOG   1"

.SS "#define HAVE_M_PI   1"

.SS "#define HAVE_MALLOC   1"

.SS "#define HAVE_MATH_H   1"

.SS "#define HAVE_MEMCMP   1"

.SS "#define HAVE_MEMCPY   1"

.SS "#define HAVE_MEMMOVE   1"

.SS "#define HAVE_MEMSET   1"

.SS "#define HAVE_NANOSLEEP   1"

.SS "#define HAVE_POW   1"

.SS "#define HAVE_PUTENV   1"

.SS "#define HAVE_QSORT   1"

.SS "#define HAVE_REALLOC   1"

.SS "#define HAVE_SCALBN   1"

.SS "#define HAVE_SETENV   1"

.SS "#define HAVE_SETENV   1"

.SS "#define HAVE_SETJMP   1"

.SS "#define HAVE_SIGNAL_H   1"

.SS "#define HAVE_SIN   1"

.SS "#define HAVE_SINF   1"

.SS "#define HAVE_SQRT   1"

.SS "#define HAVE_SQRTF   1"

.SS "#define HAVE_STDINT_H   1"

.SS "#define HAVE_STDIO_H   1"

.SS "#define HAVE_STRCASECMP   1"

.SS "#define HAVE_STRCHR   1"

.SS "#define HAVE_STRCMP   1"

.SS "#define HAVE_STRDUP   1"

.SS "#define HAVE_STRING_H   1"

.SS "#define HAVE_STRLCAT   1"

.SS "#define HAVE_STRLCPY   1"

.SS "#define HAVE_STRLEN   1"

.SS "#define HAVE_STRNCASECMP   1"

.SS "#define HAVE_STRNCMP   1"

.SS "#define HAVE_STRRCHR   1"

.SS "#define HAVE_STRSTR   1"

.SS "#define HAVE_STRTOD   1"

.SS "#define HAVE_STRTOL   1"

.SS "#define HAVE_STRTOLL   1"

.SS "#define HAVE_STRTOUL   1"

.SS "#define HAVE_STRTOULL   1"

.SS "#define HAVE_SYS_TYPES_H   1"

.SS "#define HAVE_TAN   1"

.SS "#define HAVE_TANF   1"

.SS "#define HAVE_UNSETENV   1"

.SS "#define HAVE_VSNPRINTF   1"

.SS "#define HAVE_VSSCANF   1"

.SS "#define LACKS_SYS_MMAN_H   1"

.SS "#define SDL_AUDIO_DRIVER_PSP   1"

.SS "#define SDL_config_h_"

.SS "#define SDL_FILESYSTEM_DUMMY   1"

.SS "#define SDL_HAPTIC_DISABLED   1"

.SS "#define SDL_JOYSTICK_PSP   1"

.SS "#define SDL_LOADSO_DISABLED   1"

.SS "#define SDL_POWER_PSP   1"

.SS "#define SDL_THREAD_PSP   1"

.SS "#define SDL_TIMERS_PSP   1"

.SS "#define SDL_VIDEO_DRIVER_PSP   1"

.SS "#define SDL_VIDEO_RENDER_PSP   1"

.SS "#define STDC_HEADERS   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
