.TH "D:/RayTracing/include/SDL_bits.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/include/SDL_bits.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL_stdinc\&.h'\fP
.br
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSDL_FORCE_INLINE\fP int \fBSDL_MostSignificantBitIndex32\fP (\fBUint32\fP \fBx\fP)"
.br
.ti -1c
.RI "\fBSDL_FORCE_INLINE\fP \fBSDL_bool\fP \fBSDL_HasExactlyOneBitSet32\fP (\fBUint32\fP \fBx\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for fiddling with bits and bitmasks\&.
.SH "Function Documentation"
.PP 
.SS "\fBSDL_FORCE_INLINE\fP \fBSDL_bool\fP SDL_HasExactlyOneBitSet32 (\fBUint32\fP x)"

.SS "\fBSDL_FORCE_INLINE\fP int SDL_MostSignificantBitIndex32 (\fBUint32\fP x)"
Get the index of the most significant bit\&. Result is undefined when called with 0\&. This operation can also be stated as 'count leading zeroes' and 'log base 2'\&.
.PP
\fBReturns\fP
.RS 4
the index of the most significant bit, or -1 if the value is 0\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
