.TH "SDL_WindowShapeParams" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_WindowShapeParams \- A union containing parameters for shaped windows\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_shape\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUint8\fP \fBbinarizationCutoff\fP"
.br
.RI "A cutoff alpha value for binarization of the window shape's alpha channel\&. "
.ti -1c
.RI "\fBSDL_Color\fP \fBcolorKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A union containing parameters for shaped windows\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBUint8\fP SDL_WindowShapeParams::binarizationCutoff"

.PP
A cutoff alpha value for binarization of the window shape's alpha channel\&. 
.SS "\fBSDL_Color\fP SDL_WindowShapeParams::colorKey"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
