.TH "SDL_AssertData" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_AssertData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_assert\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBalways_ignore\fP"
.br
.ti -1c
.RI "unsigned int \fBtrigger_count\fP"
.br
.ti -1c
.RI "const char * \fBcondition\fP"
.br
.ti -1c
.RI "const char * \fBfilename\fP"
.br
.ti -1c
.RI "int \fBlinenum\fP"
.br
.ti -1c
.RI "const char * \fBfunction\fP"
.br
.ti -1c
.RI "const struct \fBSDL_AssertData\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int SDL_AssertData::always_ignore"

.SS "const char* SDL_AssertData::condition"

.SS "const char* SDL_AssertData::filename"

.SS "const char* SDL_AssertData::function"

.SS "int SDL_AssertData::linenum"

.SS "const struct \fBSDL_AssertData\fP* SDL_AssertData::next"

.SS "unsigned int SDL_AssertData::trigger_count"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
