.TH "SDL_ControllerTouchpadEvent" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_ControllerTouchpadEvent \- Game controller touchpad event structure (event\&.ctouchpad\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUint32\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBtimestamp\fP"
.br
.ti -1c
.RI "\fBSDL_JoystickID\fP \fBwhich\fP"
.br
.ti -1c
.RI "\fBSint32\fP \fBtouchpad\fP"
.br
.ti -1c
.RI "\fBSint32\fP \fBfinger\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBpressure\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Game controller touchpad event structure (event\&.ctouchpad\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "\fBSint32\fP SDL_ControllerTouchpadEvent::finger"
The index of the finger on the touchpad 
.SS "float SDL_ControllerTouchpadEvent::pressure"
Normalized in the range 0\&.\&.\&.1 
.SS "\fBUint32\fP SDL_ControllerTouchpadEvent::timestamp"
In milliseconds, populated using \fBSDL_GetTicks()\fP 
.SS "\fBSint32\fP SDL_ControllerTouchpadEvent::touchpad"
The index of the touchpad 
.SS "\fBUint32\fP SDL_ControllerTouchpadEvent::type"
\fBSDL_CONTROLLERTOUCHPADDOWN\fP or \fBSDL_CONTROLLERTOUCHPADMOTION\fP or \fBSDL_CONTROLLERTOUCHPADUP\fP 
.SS "\fBSDL_JoystickID\fP SDL_ControllerTouchpadEvent::which"
The joystick instance id 
.SS "float SDL_ControllerTouchpadEvent::x"
Normalized in the range 0\&.\&.\&.1 with 0 being on the left 
.SS "float SDL_ControllerTouchpadEvent::y"
Normalized in the range 0\&.\&.\&.1 with 0 being at the top 

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
