.TH "D:/RayTracing/include/SDL_opengles2_khrplatform.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/include/SDL_opengles2_khrplatform.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKHRONOS_APICALL\fP"
.br
.ti -1c
.RI "#define \fBKHRONOS_APIENTRY\fP"
.br
.ti -1c
.RI "#define \fBKHRONOS_APIATTRIBUTES\fP"
.br
.ti -1c
.RI "#define \fBKHRONOS_SUPPORT_INT64\fP   1"
.br
.ti -1c
.RI "#define \fBKHRONOS_SUPPORT_FLOAT\fP   1"
.br
.ti -1c
.RI "#define \fBKHRONOS_MAX_ENUM\fP   0x7FFFFFFF"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBint32_t\fP \fBkhronos_int32_t\fP"
.br
.ti -1c
.RI "typedef \fBuint32_t\fP \fBkhronos_uint32_t\fP"
.br
.ti -1c
.RI "typedef \fBint64_t\fP \fBkhronos_int64_t\fP"
.br
.ti -1c
.RI "typedef \fBuint64_t\fP \fBkhronos_uint64_t\fP"
.br
.ti -1c
.RI "typedef signed char \fBkhronos_int8_t\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBkhronos_uint8_t\fP"
.br
.ti -1c
.RI "typedef signed short int \fBkhronos_int16_t\fP"
.br
.ti -1c
.RI "typedef unsigned short int \fBkhronos_uint16_t\fP"
.br
.ti -1c
.RI "typedef signed long int \fBkhronos_intptr_t\fP"
.br
.ti -1c
.RI "typedef unsigned long int \fBkhronos_uintptr_t\fP"
.br
.ti -1c
.RI "typedef signed long int \fBkhronos_ssize_t\fP"
.br
.ti -1c
.RI "typedef unsigned long int \fBkhronos_usize_t\fP"
.br
.ti -1c
.RI "typedef float \fBkhronos_float_t\fP"
.br
.ti -1c
.RI "typedef \fBkhronos_uint64_t\fP \fBkhronos_utime_nanoseconds_t\fP"
.br
.ti -1c
.RI "typedef \fBkhronos_int64_t\fP \fBkhronos_stime_nanoseconds_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBkhronos_boolean_enum_t\fP { \fBKHRONOS_FALSE\fP = 0, \fBKHRONOS_TRUE\fP = 1, \fBKHRONOS_BOOLEAN_ENUM_FORCE_SIZE\fP = KHRONOS_MAX_ENUM }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define KHRONOS_APIATTRIBUTES"

.SS "#define KHRONOS_APICALL"

.SS "#define KHRONOS_APIENTRY"

.SS "#define KHRONOS_MAX_ENUM   0x7FFFFFFF"

.SS "#define KHRONOS_SUPPORT_FLOAT   1"

.SS "#define KHRONOS_SUPPORT_INT64   1"

.SH "Typedef Documentation"
.PP 
.SS "typedef float \fBkhronos_float_t\fP"

.SS "typedef signed short int \fBkhronos_int16_t\fP"

.SS "typedef \fBint32_t\fP \fBkhronos_int32_t\fP"

.SS "typedef \fBint64_t\fP \fBkhronos_int64_t\fP"

.SS "typedef signed char \fBkhronos_int8_t\fP"

.SS "typedef signed long int \fBkhronos_intptr_t\fP"

.SS "typedef signed long int \fBkhronos_ssize_t\fP"

.SS "typedef \fBkhronos_int64_t\fP \fBkhronos_stime_nanoseconds_t\fP"

.SS "typedef unsigned short int \fBkhronos_uint16_t\fP"

.SS "typedef \fBuint32_t\fP \fBkhronos_uint32_t\fP"

.SS "typedef \fBuint64_t\fP \fBkhronos_uint64_t\fP"

.SS "typedef unsigned char \fBkhronos_uint8_t\fP"

.SS "typedef unsigned long int \fBkhronos_uintptr_t\fP"

.SS "typedef unsigned long int \fBkhronos_usize_t\fP"

.SS "typedef \fBkhronos_uint64_t\fP \fBkhronos_utime_nanoseconds_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBkhronos_boolean_enum_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKHRONOS_FALSE \fP\fP
.TP
\fB\fIKHRONOS_TRUE \fP\fP
.TP
\fB\fIKHRONOS_BOOLEAN_ENUM_FORCE_SIZE \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
