.TH "D:/RayTracing/include/SDL_config_winrt.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/include/SDL_config_winrt.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL_platform\&.h'\fP
.br
\fC#include <sdkddkver\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDL_config_h_\fP"
.br
.ti -1c
.RI "#define \fBNTDDI_WINBLUE\fP   0x06030000"
.br
.ti -1c
.RI "#define \fBNTDDI_WIN10\fP   0x0A000000"
.br
.ti -1c
.RI "#define \fB_SIZE_T_DEFINED_\fP"
.br
.ti -1c
.RI "#define \fBSIZEOF_VOIDP\fP   4"
.br
.ti -1c
.RI "#define \fBHAVE_DXGI_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LIBC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDIO_H\fP   1"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CTYPE_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MATH_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FLOAT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIGNAL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_REALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FREE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ALLOCA\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_QSORT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ABS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMSET\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMMOVE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRLEN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE__STRREV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE__STRUPR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCHR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRRCHR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRSTR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOUL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOD\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATOI\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATOF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRNCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE__STRICMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE__STRNICMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_VSNPRINTF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_M_PI\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATAN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATAN2\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CEIL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE__COPYSIGN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COSF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FABS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FLOOR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LOG\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_POW\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE__SCALB\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SINF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SQRT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SQRTF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_TAN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_TANF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE__FSEEKI64\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_XAUDIO2\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_DISK\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_JOYSTICK_DISABLED\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_HAPTIC_DISABLED\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_LOADSO_WINDOWS\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_THREAD_STDCPP\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_TIMER_WINDOWS\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_WINRT\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_ES2\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_EGL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_RENDER_D3D11\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_RENDER_OGL_ES2\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_POWER_WINRT\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_ASSEMBLY_ROUTINES\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef signed char \fBint8_t\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuint8_t\fP"
.br
.ti -1c
.RI "typedef signed short \fBint16_t\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBuint16_t\fP"
.br
.ti -1c
.RI "typedef signed int \fBint32_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBuint32_t\fP"
.br
.ti -1c
.RI "typedef signed long long \fBint64_t\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBuint64_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBsize_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBuintptr_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _SIZE_T_DEFINED_"

.SS "#define HAVE__COPYSIGN   1"

.SS "#define HAVE__FSEEKI64   1"

.SS "#define HAVE__SCALB   1"

.SS "#define HAVE__STRICMP   1"

.SS "#define HAVE__STRNICMP   1"

.SS "#define HAVE__STRREV   1"

.SS "#define HAVE__STRUPR   1"

.SS "#define HAVE_ABS   1"

.SS "#define HAVE_ALLOCA   1"

.SS "#define HAVE_ATAN   1"

.SS "#define HAVE_ATAN2   1"

.SS "#define HAVE_ATOF   1"

.SS "#define HAVE_ATOI   1"

.SS "#define HAVE_CALLOC   1"

.SS "#define HAVE_CEIL   1"

.SS "#define HAVE_COS   1"

.SS "#define HAVE_COSF   1"

.SS "#define HAVE_CTYPE_H   1"

.SS "#define HAVE_DXGI_H   1"

.SS "#define HAVE_FABS   1"

.SS "#define HAVE_FLOAT_H   1"

.SS "#define HAVE_FLOOR   1"

.SS "#define HAVE_FREE   1"

.SS "#define HAVE_LIBC   1"

.SS "#define HAVE_LOG   1"

.SS "#define HAVE_M_PI   1"

.SS "#define HAVE_MALLOC   1"

.SS "#define HAVE_MATH_H   1"

.SS "#define HAVE_MEMCMP   1"

.SS "#define HAVE_MEMCPY   1"

.SS "#define HAVE_MEMMOVE   1"

.SS "#define HAVE_MEMSET   1"

.SS "#define HAVE_POW   1"

.SS "#define HAVE_QSORT   1"

.SS "#define HAVE_REALLOC   1"

.SS "#define HAVE_SIGNAL_H   1"

.SS "#define HAVE_SIN   1"

.SS "#define HAVE_SINF   1"

.SS "#define HAVE_SQRT   1"

.SS "#define HAVE_SQRTF   1"

.SS "#define HAVE_STDIO_H   1"

.SS "#define HAVE_STRCHR   1"

.SS "#define HAVE_STRCMP   1"

.SS "#define HAVE_STRING_H   1"

.SS "#define HAVE_STRLEN   1"

.SS "#define HAVE_STRNCMP   1"

.SS "#define HAVE_STRRCHR   1"

.SS "#define HAVE_STRSTR   1"

.SS "#define HAVE_STRTOD   1"

.SS "#define HAVE_STRTOL   1"

.SS "#define HAVE_STRTOUL   1"

.SS "#define HAVE_TAN   1"

.SS "#define HAVE_TANF   1"

.SS "#define HAVE_VSNPRINTF   1"

.SS "#define NTDDI_WIN10   0x0A000000"

.SS "#define NTDDI_WINBLUE   0x06030000"

.SS "#define SDL_ASSEMBLY_ROUTINES   1"

.SS "#define SDL_AUDIO_DRIVER_DISK   1"

.SS "#define SDL_AUDIO_DRIVER_DUMMY   1"

.SS "#define SDL_AUDIO_DRIVER_XAUDIO2   1"

.SS "#define SDL_config_h_"

.SS "#define SDL_HAPTIC_DISABLED   1"

.SS "#define SDL_JOYSTICK_DISABLED   1"

.SS "#define SDL_LOADSO_WINDOWS   1"

.SS "#define SDL_POWER_WINRT   1"

.SS "#define SDL_THREAD_STDCPP   1"

.SS "#define SDL_TIMER_WINDOWS   1"

.SS "#define SDL_VIDEO_DRIVER_DUMMY   1"

.SS "#define SDL_VIDEO_DRIVER_WINRT   1"

.SS "#define SDL_VIDEO_OPENGL_EGL   1"

.SS "#define SDL_VIDEO_OPENGL_ES2   1"

.SS "#define SDL_VIDEO_RENDER_D3D11   1"

.SS "#define SDL_VIDEO_RENDER_OGL_ES2   1"

.SS "#define SIZEOF_VOIDP   4"

.SS "#define STDC_HEADERS   1"

.SH "Typedef Documentation"
.PP 
.SS "typedef signed short \fBint16_t\fP"

.SS "typedef signed int \fBint32_t\fP"

.SS "typedef signed long long \fBint64_t\fP"

.SS "typedef signed char \fBint8_t\fP"

.SS "typedef unsigned int \fBsize_t\fP"

.SS "typedef unsigned short \fBuint16_t\fP"

.SS "typedef unsigned int \fBuint32_t\fP"

.SS "typedef unsigned long long \fBuint64_t\fP"

.SS "typedef unsigned char \fBuint8_t\fP"

.SS "typedef unsigned int \fBuintptr_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
