.TH "D:/RayTracing/include/SDL_name.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/include/SDL_name.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDL_NAME\fP(X)   SDL_##X"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SDL_NAME(X)   SDL_##X"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
