.TH "SDL_JoyHatEvent" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_JoyHatEvent \- Joystick hat position change event structure (event\&.jhat\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUint32\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBtimestamp\fP"
.br
.ti -1c
.RI "\fBSDL_JoystickID\fP \fBwhich\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBhat\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBvalue\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBpadding1\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBpadding2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Joystick hat position change event structure (event\&.jhat\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "\fBUint8\fP SDL_JoyHatEvent::hat"
The joystick hat index 
.SS "\fBUint8\fP SDL_JoyHatEvent::padding1"

.SS "\fBUint8\fP SDL_JoyHatEvent::padding2"

.SS "\fBUint32\fP SDL_JoyHatEvent::timestamp"
In milliseconds, populated using \fBSDL_GetTicks()\fP 
.SS "\fBUint32\fP SDL_JoyHatEvent::type"
\fBSDL_JOYHATMOTION\fP 
.SS "\fBUint8\fP SDL_JoyHatEvent::value"
The hat position value\&. 
.PP
\fBSee also\fP
.RS 4
\fBSDL_HAT_LEFTUP\fP \fBSDL_HAT_UP\fP \fBSDL_HAT_RIGHTUP\fP 
.PP
\fBSDL_HAT_LEFT\fP \fBSDL_HAT_CENTERED\fP \fBSDL_HAT_RIGHT\fP 
.PP
\fBSDL_HAT_LEFTDOWN\fP \fBSDL_HAT_DOWN\fP \fBSDL_HAT_RIGHTDOWN\fP
.RE
.PP
Note that zero means the POV is centered\&. 
.SS "\fBSDL_JoystickID\fP SDL_JoyHatEvent::which"
The joystick instance id 

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
