.TH "D:/RayTracing/include/SDL_config_macosx.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/include/SDL_config_macosx.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL_platform\&.h'\fP
.br
\fC#include <AvailabilityMacros\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDL_config_h_\fP"
.br
.ti -1c
.RI "#define \fBSIZEOF_VOIDP\fP   4"
.br
.ti -1c
.RI "#define \fBHAVE_ALLOCA_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDIO_H\fP   1"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CTYPE_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MATH_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIGNAL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_REALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FREE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ALLOCA\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_GETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_PUTENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNSETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_QSORT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ABS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_BCOPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMSET\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMMOVE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRLEN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRLCPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRLCAT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRDUP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCHR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRRCHR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRSTR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOUL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOLL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOULL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOD\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATOI\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATOF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRNCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCASECMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRNCASECMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_VSSCANF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_VSNPRINTF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CEIL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COPYSIGN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COSF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FABS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FLOOR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LOG\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_POW\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SCALBN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SINF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SQRT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SQRTF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_TAN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_TANF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIGACTION\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SETJMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_NANOSLEEP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYSCONF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYSCTLBYNAME\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATAN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATAN2\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ACOS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ASIN\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_COREAUDIO\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_DISK\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_JOYSTICK_IOKIT\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_HAPTIC_IOKIT\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_LOADSO_DLOPEN\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_THREAD_PTHREAD\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_THREAD_PTHREAD_RECURSIVE_MUTEX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_TIMER_UNIX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_COCOA\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC\fP   '/usr/X11R6/lib/libX11\&.6\&.dylib'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT\fP   '/usr/X11R6/lib/libXext\&.6\&.dylib'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XINERAMA\fP   '/usr/X11R6/lib/libXinerama\&.1\&.dylib'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2\fP   '/usr/X11R6/lib/libXi\&.6\&.dylib'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR\fP   '/usr/X11R6/lib/libXrandr\&.2\&.dylib'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XSS\fP   '/usr/X11R6/lib/libXss\&.1\&.dylib'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XVIDMODE\fP   '/usr/X11R6/lib/libXxf86vm\&.1\&.dylib'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XDBE\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XINERAMA\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XRANDR\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XSCRNSAVER\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XSHAPE\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XVIDMODE\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_HAS_XKBKEYCODETOKEYSYM\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_RENDER_OGL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_CGL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_GLX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_VULKAN\fP   0"
.br
.ti -1c
.RI "#define \fBSDL_POWER_MACOSX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_FILESYSTEM_COCOA\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_ASSEMBLY_ROUTINES\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HAVE_ABS   1"

.SS "#define HAVE_ACOS   1"

.SS "#define HAVE_ALLOCA   1"

.SS "#define HAVE_ALLOCA_H   1"

.SS "#define HAVE_ASIN   1"

.SS "#define HAVE_ATAN   1"

.SS "#define HAVE_ATAN2   1"

.SS "#define HAVE_ATOF   1"

.SS "#define HAVE_ATOI   1"

.SS "#define HAVE_BCOPY   1"

.SS "#define HAVE_CALLOC   1"

.SS "#define HAVE_CEIL   1"

.SS "#define HAVE_COPYSIGN   1"

.SS "#define HAVE_COS   1"

.SS "#define HAVE_COSF   1"

.SS "#define HAVE_CTYPE_H   1"

.SS "#define HAVE_FABS   1"

.SS "#define HAVE_FLOOR   1"

.SS "#define HAVE_FREE   1"

.SS "#define HAVE_GETENV   1"

.SS "#define HAVE_INTTYPES_H   1"

.SS "#define HAVE_LOG   1"

.SS "#define HAVE_MALLOC   1"

.SS "#define HAVE_MATH_H   1"

.SS "#define HAVE_MEMCMP   1"

.SS "#define HAVE_MEMCPY   1"

.SS "#define HAVE_MEMMOVE   1"

.SS "#define HAVE_MEMSET   1"

.SS "#define HAVE_NANOSLEEP   1"

.SS "#define HAVE_POW   1"

.SS "#define HAVE_PUTENV   1"

.SS "#define HAVE_QSORT   1"

.SS "#define HAVE_REALLOC   1"

.SS "#define HAVE_SCALBN   1"

.SS "#define HAVE_SETENV   1"

.SS "#define HAVE_SETJMP   1"

.SS "#define HAVE_SIGACTION   1"

.SS "#define HAVE_SIGNAL_H   1"

.SS "#define HAVE_SIN   1"

.SS "#define HAVE_SINF   1"

.SS "#define HAVE_SQRT   1"

.SS "#define HAVE_SQRTF   1"

.SS "#define HAVE_STDINT_H   1"

.SS "#define HAVE_STDIO_H   1"

.SS "#define HAVE_STRCASECMP   1"

.SS "#define HAVE_STRCHR   1"

.SS "#define HAVE_STRCMP   1"

.SS "#define HAVE_STRDUP   1"

.SS "#define HAVE_STRING_H   1"

.SS "#define HAVE_STRLCAT   1"

.SS "#define HAVE_STRLCPY   1"

.SS "#define HAVE_STRLEN   1"

.SS "#define HAVE_STRNCASECMP   1"

.SS "#define HAVE_STRNCMP   1"

.SS "#define HAVE_STRRCHR   1"

.SS "#define HAVE_STRSTR   1"

.SS "#define HAVE_STRTOD   1"

.SS "#define HAVE_STRTOL   1"

.SS "#define HAVE_STRTOLL   1"

.SS "#define HAVE_STRTOUL   1"

.SS "#define HAVE_STRTOULL   1"

.SS "#define HAVE_SYS_TYPES_H   1"

.SS "#define HAVE_SYSCONF   1"

.SS "#define HAVE_SYSCTLBYNAME   1"

.SS "#define HAVE_TAN   1"

.SS "#define HAVE_TANF   1"

.SS "#define HAVE_UNSETENV   1"

.SS "#define HAVE_VSNPRINTF   1"

.SS "#define HAVE_VSSCANF   1"

.SS "#define SDL_ASSEMBLY_ROUTINES   1"

.SS "#define SDL_AUDIO_DRIVER_COREAUDIO   1"

.SS "#define SDL_AUDIO_DRIVER_DISK   1"

.SS "#define SDL_AUDIO_DRIVER_DUMMY   1"

.SS "#define SDL_config_h_"

.SS "#define SDL_FILESYSTEM_COCOA   1"

.SS "#define SDL_HAPTIC_IOKIT   1"

.SS "#define SDL_JOYSTICK_IOKIT   1"

.SS "#define SDL_LOADSO_DLOPEN   1"

.SS "#define SDL_POWER_MACOSX   1"

.SS "#define SDL_THREAD_PTHREAD   1"

.SS "#define SDL_THREAD_PTHREAD_RECURSIVE_MUTEX   1"

.SS "#define SDL_TIMER_UNIX   1"

.SS "#define SDL_VIDEO_DRIVER_COCOA   1"

.SS "#define SDL_VIDEO_DRIVER_DUMMY   1"

.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC   '/usr/X11R6/lib/libX11\&.6\&.dylib'"

.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT   '/usr/X11R6/lib/libXext\&.6\&.dylib'"

.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XINERAMA   '/usr/X11R6/lib/libXinerama\&.1\&.dylib'"

.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2   '/usr/X11R6/lib/libXi\&.6\&.dylib'"

.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR   '/usr/X11R6/lib/libXrandr\&.2\&.dylib'"

.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XSS   '/usr/X11R6/lib/libXss\&.1\&.dylib'"

.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XVIDMODE   '/usr/X11R6/lib/libXxf86vm\&.1\&.dylib'"

.SS "#define SDL_VIDEO_DRIVER_X11_HAS_XKBKEYCODETOKEYSYM   1"

.SS "#define SDL_VIDEO_DRIVER_X11_XDBE   1"

.SS "#define SDL_VIDEO_DRIVER_X11_XINERAMA   1"

.SS "#define SDL_VIDEO_DRIVER_X11_XRANDR   1"

.SS "#define SDL_VIDEO_DRIVER_X11_XSCRNSAVER   1"

.SS "#define SDL_VIDEO_DRIVER_X11_XSHAPE   1"

.SS "#define SDL_VIDEO_DRIVER_X11_XVIDMODE   1"

.SS "#define SDL_VIDEO_OPENGL   1"

.SS "#define SDL_VIDEO_OPENGL_CGL   1"

.SS "#define SDL_VIDEO_OPENGL_GLX   1"

.SS "#define SDL_VIDEO_RENDER_OGL   1"

.SS "#define SDL_VIDEO_VULKAN   0"

.SS "#define SIZEOF_VOIDP   4"

.SS "#define STDC_HEADERS   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
