.TH "D:/RayTracing/include/SDL_opengles2.h" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RayTracing/include/SDL_opengles2.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL_config\&.h'\fP
.br
\fC#include <GLES2/gl2platform\&.h>\fP
.br
\fC#include <GLES2/gl2\&.h>\fP
.br
\fC#include <GLES2/gl2ext\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAPIENTRY\fP   \fBGL_APIENTRY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a simple file to encapsulate the OpenGL ES 2\&.0 API headers\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define APIENTRY   \fBGL_APIENTRY\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
