.TH "SDL_Point" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Point
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_rect\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The structure that defines a point (integer)
.PP
\fBSee also\fP
.RS 4
\fBSDL_EnclosePoints\fP 
.PP
\fBSDL_PointInRect\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "int SDL_Point::x"

.SS "int SDL_Point::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
