.TH "SDL_WindowShapeMode" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_WindowShapeMode \- A struct that tags the \fBSDL_WindowShapeParams\fP union with an enum describing the type of its contents\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_shape\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWindowShapeMode\fP \fBmode\fP"
.br
.RI "The mode of these window-shape parameters\&. "
.ti -1c
.RI "\fBSDL_WindowShapeParams\fP \fBparameters\fP"
.br
.RI "Window-shape parameters\&. "
.in -1c
.SH "Detailed Description"
.PP 
A struct that tags the \fBSDL_WindowShapeParams\fP union with an enum describing the type of its contents\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBWindowShapeMode\fP SDL_WindowShapeMode::mode"

.PP
The mode of these window-shape parameters\&. 
.SS "\fBSDL_WindowShapeParams\fP SDL_WindowShapeMode::parameters"

.PP
Window-shape parameters\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
