.TH "SDL_FPoint" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_FPoint
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_rect\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The structure that defines a point (floating point)
.PP
\fBSee also\fP
.RS 4
\fBSDL_EnclosePoints\fP 
.PP
\fBSDL_PointInRect\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "float SDL_FPoint::x"

.SS "float SDL_FPoint::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
