.TH "SDL_JoystickGUID" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_JoystickGUID
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_joystick\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUint8\fP \fBdata\fP [16]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBUint8\fP SDL_JoystickGUID::data[16]"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
