.TH "SDLTest_TestCaseReference" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_TestCaseReference
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_test_harness\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSDLTest_TestCaseFp\fP \fBtestCase\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBdescription\fP"
.br
.ti -1c
.RI "int \fBenabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds information about a single test case\&. 
.SH "Member Data Documentation"
.PP 
.SS "const char* SDLTest_TestCaseReference::description"

.SS "int SDLTest_TestCaseReference::enabled"

.SS "const char* SDLTest_TestCaseReference::name"

.SS "\fBSDLTest_TestCaseFp\fP SDLTest_TestCaseReference::testCase"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
