.TH "SDLTest_TestSuiteReference" 3 "Mon Jan 24 2022" "Version 1.0" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_TestSuiteReference
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_test_harness\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBSDLTest_TestCaseSetUpFp\fP \fBtestSetUp\fP"
.br
.ti -1c
.RI "const \fBSDLTest_TestCaseReference\fP ** \fBtestCases\fP"
.br
.ti -1c
.RI "\fBSDLTest_TestCaseTearDownFp\fP \fBtestTearDown\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds information about a test suite (multiple test cases)\&. 
.SH "Member Data Documentation"
.PP 
.SS "const char* SDLTest_TestSuiteReference::name"

.SS "const \fBSDLTest_TestCaseReference\fP** SDLTest_TestSuiteReference::testCases"

.SS "\fBSDLTest_TestCaseSetUpFp\fP SDLTest_TestSuiteReference::testSetUp"

.SS "\fBSDLTest_TestCaseTearDownFp\fP SDLTest_TestSuiteReference::testTearDown"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
